default: &default
  adapter: postgresql
  database: dropnote
  host: localhost

development:
  <<: *default
  database: dropnote_development
  min_messages: warning

test:
  <<: *default
  database: dropnote_test
